### PR TITLE
add a readme for creating a custom repo

### PR DESCRIPTION
**Pull request by steadfasterX**

### CODE REVIEW

**Comment by Zanthed** [comment]
Can you please squash these commits into one?

**Comment by steadfasterX** [comment]
ah yea sure. done ;)

**Comment by steadfasterX** [comment]
i added a second commit to split the regular readme from the third party section. hope thats fine. if not let me know and I squash that again

**Comment by thestinger** [comment]
This will need to be updated due to the app repository rewrite bringing substantial changes. Most people don't need to use the legacy metadata.

**Comment by thestinger** [comment]
Also, should probably explain how to use the deploy script and nginx configuration we use. We combine this with our OS update server so it's spread out across this repository and the releases.grapheneos.org repository.

**Pull request closed without merging**
